use bevy::prelude::*;

pub(crate) const WINDOW_WIDTH: u32 = 1180;
pub(crate) const WINDOW_HEIGHT: u32 = 760;
pub(crate) const PLAYER_START_X: f32 = -260.0;
pub(crate) const PLAYER_Y: f32 = -250.0;
pub(crate) const PLAYER_SPEED: f32 = 62.0;
pub(crate) const SPAWN_AHEAD_DISTANCE: f32 = 560.0;
pub(crate) const PLAYER_ATTACK_RANGE: f32 = 58.0;
pub(crate) const ENEMY_ATTACK_RANGE: f32 = 52.0;
pub(crate) const INVENTORY_SIZE: usize = 24;
pub(crate) const STASH_SIZE: usize = 30;
pub(crate) const EQUIPMENT_SLOT_COUNT: usize = 8;
pub(crate) const CRAFTING_SLOT_COUNT: usize = 5;
pub(crate) const INVENTORY_CELL_SIZE: f32 = 38.0;
pub(crate) const MAP_PROGRESS_LEFT: f32 = 254.0;
pub(crate) const MAP_PROGRESS_WIDTH: f32 = 284.0;
pub(crate) const TOOLTIP_WIDTH: f32 = 278.0;
pub(crate) const TOOLTIP_PADDING: f32 = 12.0;
pub(crate) const BOTTOM_BUTTON_SIZE: Vec2 = Vec2::new(82.0, 46.0);
